%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 2  

imu_topic: "/mavros/imu/data"
image0_topic: "/camera/infra1/image_rect_raw"
image1_topic: "/camera/infra2/image_rect_raw"
output_path: "/home/dji/output/"

cam0_calib: "left (PX4).yaml"
cam1_calib: "right (PX4).yaml"
image_width: 640
image_height: 480
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 0.06092314, -0.13148428,  0.98944442, -0.00036943,
         -0.99426913, -0.09523874,  0.04856423,  0.0000518, 
         0.08784801, -0.98673272, -0.136533,   -0.00014735,
         0.,          0.,          0.,          1.        ]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 0.07970617, -0.13235425,  0.98799255,  0.00127319,
         -0.9931707,  -0.09525862,  0.0673628,  -0.05265596,
          0.08519905, -0.98661449, -0.13904306,  0.00470893,
          0.,          0.,          0.,          1.        ]

#Multiple thread support
multiple_thread: 2
use_gpu: 1
use_gpu_acc_flow: 1

#feature traker paprameters
max_cnt: 50            # max feature number in feature tracking
min_dist: 12            # min distance between two features 
freq: 30                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 0           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.03  # max solver itration time (ms), to guarantee real time
max_num_iterations: 6   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 1.1425147371878221e-03            # accelerometer measurement noise standard deviation. #0.001865  "0.00147"
gyr_n: 6.5701493361719325e-04      # gyroscope measurement noise standard deviation. #0.0018685    "0.0002443461"
acc_w: 3.2672759217670199e-06     # accelerometer bias random work noise standard deviation.  #0.0002   "0.00098"
gyr_w: 3.4361030791828315e-06       # gyroscope bias random work noise standard deviation.  #0.000004    "0.01466077"
g_norm: 9.805         # gravity magnitude 9.805

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: -0.000135842891756                           # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/dji/output/pose_graph/" # save and load path
save_image: 0                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
