%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 2  

imu_topic: "/imu/data"
image0_topic: "/camera/infra1/image_rect_raw"
image1_topic: "/camera/infra2/image_rect_raw"
output_path: "/home/dji/output/"

cam0_calib: "left (realsense).yaml"
cam1_calib: "right (realsense).yaml"
image_width: 640
image_height: 480
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 0.99992636,  0.00570922, -0.0107093,   0.00511273,
          -0.00578268,  0.99995988, -0.00684116,  0.00329164,
          0.01066982,  0.00690259,  0.99991925,  0.00424374,
          0.,          0.,          0.,          1.        ]


body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 0.99969968,  0.00601838, -0.0237554,   0.05872747,
          -0.0061933,   0.9999542,  -0.00729656,  0.00295727,
          0.0237104,   0.00744149,  0.99969117,  0.00475325,
          0.,          0.,          0.,          1.        ]
#Multiple thread support
multiple_thread: 2
use_gpu: 1
use_gpu_acc_flow: 1

#feature traker paprameters
max_cnt: 50            # max feature number in feature tracking
min_dist: 12            # min distance between two features 
freq: 30                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 0           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.03  # max solver itration time (ms), to guarantee real time
max_num_iterations: 6   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.0108306596           # accelerometer measurement noise standard deviation. #0.001865  "0.00147"
gyr_n: 0.001903801       # gyroscope measurement noise standard deviation. #0.0018685    "0.0002443461"
acc_w: 5.573159e-05     # accelerometer bias random work noise standard deviation.  #0.0002   "0.00098"
gyr_w: 8.17677e-06       # gyroscope bias random work noise standard deviation.  #0.000004    "0.01466077"
g_norm: 9.805         # gravity magnitude 9.805

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: 0.00                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/dji/output/pose_graph/" # save and load path
save_image: 0                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
